#!/usr/bin/env python3

import argparse
from os import path, walk
from collections import defaultdict
from ebooklib import epub


def main(args):
  db = defaultdict(lambda: [])

  for base in args.dirs:
    for root, _, files in walk(base):
      for file in files:
        if file.endswith('.epub'):
          fname = path.join(root, file)
          book = epub.read_epub(fname)
          if book.language == 'en':
            pub = {}
            pub['version'] = book.version
            pub['title'] = book.title
            pub['fname'] = fname
            authors = []
            for author in book.get_metadata('DC', 'creator'):
              if isinstance(author, tuple):
                author = author[0]
              authors.append(author)
            pub['authors'] = authors
            db[book.uid].append(pub)

  for item in db.keys():
    db[item].sort(key=lambda pub: pub['version'], reverse=True)

  for item in db.keys():
    print(path.realpath(db[item][0]['fname']))
  return 0


if __name__ == "__main__":
  parser = argparse.ArgumentParser(prog='', description='', epilog='')
  parser.add_argument("dirs", nargs='*', default=['.'], help="Directory to scan for epub files")
  args = parser.parse_args()
  exit(main(args))
